package output

import (
	"fmt"
	"os"
	"strings"

	"github.com/sharpner/gh-ai-review/review"
)

// PrintResult writes a review result to stdout.
func PrintResult(r review.Result) {
	_, _ = fmt.Fprintf(os.Stdout, "## %s\n\n%s\n\nVerdict: %s\n", r.Label, r.Body, r.Verdict)
}

// PrintResults writes multiple review results to stdout.
func PrintResults(results []review.Result) {
	for i, r := range results {
		if i > 0 {
			_, _ = fmt.Fprintln(os.Stdout, "---")
		}
		PrintResult(r)
	}
}

// PrintDryRun writes the prompt that would be sent to Gemini.
func PrintDryRun(prompt string) {
	_, _ = fmt.Fprintln(os.Stdout, "=== DRY RUN — Prompt that would be sent to Gemini ===")
	_, _ = fmt.Fprintln(os.Stdout)
	_, _ = fmt.Fprintln(os.Stdout, prompt)
}

// FormatCombinedComment combines multiple results into a single PR comment with metadata footer.
func FormatCombinedComment(results []review.Result, model string, tokens, prNumber int) string {
	var bodies []string
	var labels []string
	for _, r := range results {
		if r.Body != "" {
			bodies = append(bodies, r.Body)
			labels = append(labels, r.Label)
		}
	}

	combined := strings.Join(bodies, "\n\n---\n\n")
	combined += fmt.Sprintf("\n\n---\n*Generated by Gemini (%s) | Reviews: %s | ~%d tokens context*\n*Run: `gh ai-review %d`*",
		model, strings.Join(labels, ", "), tokens, prNumber)

	return combined
}

// FormatAgentComment formats a single agent result with metadata footer.
func FormatAgentComment(r review.Result, agentName, model string, tokens, fileCount, prNumber int) string {
	return fmt.Sprintf("%s\n\n---\n*Generated by Gemini (%s) impersonating `%s`*\n*PR #%d | %d files | ~%d tokens context*\n*Run: `gh ai-review %d --agent %s`*",
		r.Body, model, agentName, prNumber, fileCount, tokens, prNumber, agentName)
}

// PrintSummary prints a terminal summary of all review results.
func PrintSummary(results []review.Result, prNumber int, model string, tokens int, repoSlug string) {
	fmt.Fprintln(os.Stderr)
	fmt.Fprintln(os.Stderr, "==========================================")
	fmt.Fprintf(os.Stderr, "Review posted to PR #%d\n", prNumber)

	var labels []string
	for _, r := range results {
		labels = append(labels, r.Label)
	}
	fmt.Fprintf(os.Stderr, "Reviews run: %s\n", strings.Join(labels, ", "))
	fmt.Fprintln(os.Stderr, "==========================================")

	// Recommended reviewers from generic review
	for _, r := range results {
		if r.Label != "Generic Review" {
			continue
		}
		fmt.Fprintln(os.Stderr)
		fmt.Fprintln(os.Stderr, "RECOMMENDED REVIEWERS:")
		agents := review.ExtractRecommendedAgents(r.Body)
		if len(agents) > 0 {
			for _, a := range agents {
				fmt.Fprintf(os.Stderr, "  -> %s\n", a)
			}
		} else {
			fmt.Fprintln(os.Stderr, "  (none detected)")
		}
	}

	// Print verdicts
	fmt.Fprintln(os.Stderr)
	for _, r := range results {
		if r.Verdict == "" {
			continue
		}
		fmt.Fprintf(os.Stderr, "**%s:** %s\n", r.Label, r.Verdict)
	}

	// Critical issues extraction from generic review
	for _, r := range results {
		if r.Label != "Generic Review" {
			continue
		}
		issues := extractCriticalIssues(r.Body)
		if len(issues) > 0 {
			fmt.Fprintln(os.Stderr)
			fmt.Fprintln(os.Stderr, "CRITICAL ISSUES:")
			for _, issue := range issues {
				fmt.Fprintf(os.Stderr, "  %s\n", issue)
			}
		}
	}

	fmt.Fprintln(os.Stderr)
	fmt.Fprintln(os.Stderr, "==========================================")
	fmt.Fprintln(os.Stderr, "NEXT STEPS:")
	fmt.Fprintln(os.Stderr, "  1. Run recommended Claude reviewers (or use --full)")
	fmt.Fprintln(os.Stderr, "  2. E2E test: make prod-local")
	fmt.Fprintln(os.Stderr, "  3. Run: make test")
	fmt.Fprintln(os.Stderr, "  4. Get approval, then merge")
	fmt.Fprintln(os.Stderr, "==========================================")
}

// PrintFullSummary prints a terminal summary for the full review loop.
func PrintFullSummary(results []review.Result, prNumber int, model, repoSlug string) {
	var genericCount, agentCount, focusCount int
	for _, r := range results {
		switch {
		case r.Label == "Generic Review":
			genericCount++
		case strings.HasPrefix(r.Label, "Agent:"):
			agentCount++
		default:
			focusCount++
		}
	}

	fmt.Fprintln(os.Stderr)
	fmt.Fprintln(os.Stderr, "========================================================")
	fmt.Fprintf(os.Stderr, "  Full Review Loop Complete — PR #%d\n", prNumber)
	fmt.Fprintln(os.Stderr, "========================================================")
	fmt.Fprintln(os.Stderr)
	fmt.Fprintf(os.Stderr, "  Phase 1: %d generic review (posted)\n", genericCount)
	fmt.Fprintf(os.Stderr, "  Phase 2: %d subagent impersonation(s) (posted)\n", agentCount)
	fmt.Fprintf(os.Stderr, "  Phase 3: %d focused review(s) (posted)\n", focusCount)
	fmt.Fprintln(os.Stderr)

	totalComments := genericCount + agentCount
	if focusCount > 0 {
		totalComments++ // focused reviews combined into single comment
	}
	fmt.Fprintf(os.Stderr, "  Total PR comments: %d\n", totalComments)

	if repoSlug != "" {
		fmt.Fprintf(os.Stderr, "  View: https://github.com/%s/pull/%d\n", repoSlug, prNumber)
	}

	// Per-result verdicts
	fmt.Fprintln(os.Stderr)
	for _, r := range results {
		if r.Verdict == "" {
			continue
		}
		fmt.Fprintf(os.Stderr, "  %s: %s\n", r.Label, r.Verdict)
	}

	fmt.Fprintln(os.Stderr)
	fmt.Fprintln(os.Stderr, "  NEXT: Review findings, then 'make test && make prod-local'")
	fmt.Fprintln(os.Stderr, "========================================================")
}

// extractCriticalIssues parses bullet items from the Critical Issues section of a generic review.
func extractCriticalIssues(body string) []string {
	lines := strings.Split(body, "\n")
	inSection := false
	var issues []string

	for _, line := range lines {
		if strings.Contains(line, "### Critical Issues") {
			inSection = true
			continue
		}
		if inSection && strings.HasPrefix(line, "### ") {
			break
		}
		if !inSection {
			continue
		}

		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, "- ") {
			continue
		}
		if strings.Contains(trimmed, "None found") {
			continue
		}
		issues = append(issues, trimmed)
	}

	return issues
}
